const AppConfig = {
  DENTISTRY_SUBMIT_DATA_STEPS: {
    DOCTOR_PRODUCTION: 'doctor-production',
    HYGEINIST_PRODUCTION: 'hygeinist-production',
    COLLECTIONS: 'collections',
    PATIENT_ACTIVITY: 'patient-activity',
    STAFF_COMPENSATION: 'staff-compensation',
    OCCUPANY_AND_H_P: 'occupany-and-human-physical',
    SUPPLIES_MARKETING: 'supplies-marketing',
    LABORTORY: 'labortory',
    DOCTOR_SALARY: 'doctor-salary',
    ADMINISTRATIVE_SERVICES: 'administrative-services',
    SOLVENCY_SAVINGS_ROI_FUNDS: 'solvency-savings-roi-funds',
  },
  ORTHO_SUBMIT_DATA_STEPS: {
    DOCTOR_PRODUCTION: 'doctor-production',
    COLLECTIONS: 'collections',
    PATIENT_ACTIVITY: 'patient-activity',
    STAFF_COMPENSATION: 'staff-compensation',
    OCCUPANY_AND_H_P: 'occupany-and-human-physical',
    SUPPLIES_MARKETING: 'supplies-marketing',
    LABORTORY: 'labortory',
    DOCTOR_SALARY: 'doctor-salary',
    ADMINISTRATIVE_SERVICES: 'administrative-services',
    SOLVENCY_SAVINGS_ROI_FUNDS: 'solvency-savings-roi-funds',
  },
  SCHEDULE_CLASS_STEPS: {
    REGISTER_CLASS: 'register-class',
  },
  ENERGY_CONVERSION: {
    ENERGY: 'energy',
    DIRECTION: 'direction',
    STRUCTURE_AND_SYSTEMS: 'structure-and-systems',
    COMMUNICATION_AND_COORDINATION: 'communication-and-coordination',
    ATTITUDE_AND_SKILLS: 'attitude-and-skills',
  },
  REGISTRATIONS: {
    CREATE_USER: 'create-user',
  },
  ENERGY_PROFILE: {
    DATA_RESULT: 'data-result',
    DATA_ANALYSIS: 'data-analysis',
  },
  ROUTES: {
    MAIN: '/',
    STUDENTS_SCHEDULE: '/students/schedule',
    STUDENTS_SUBMIT_DATA: '/students/submit-data',
    STUDENTS_PURCHASE_ITEMS: '/students/purchase-items',
    REPORT: '/report',
    COACHING: '/coaching',
    SUBMIT_DATA: '/submit-data',
    DENTISTRY: '/dentistry',
    ORTHO: '/ortho',
    REGISTRATION: '/registration',
    ENERGY_CONVERSION: '/energy-conversion',
    ENERGY_PROFILE: '/energy-profile',
    PROFIT_AND_LOSS: '/profit-and-loss',
    PROFIT_SCAN: '/profit-scan',
    CHART_AUDIT: '/chart-audit',
    CHART_AUDIT_REPORT: '/chart-audit-report',
    SIGN_IN: '/sign-in',
  },
};

export default AppConfig;
